import test from 'node:test';import assert from 'node:assert/strict';
import {Game,blocked,moveBody,visible,beamHits,distance} from '../src/core.js';
const advance=(g,s,input)=>{for(let t=0;t<s;t+=1/60)g.tick(1/60,typeof input==='function'?input(g):input);};
test('beam respects direction, distance and solid occluders',()=>{const p={x:0,z:0,angle:Math.PI/2},e={x:5,z:0,r:.4};assert(beamHits(p,e,[]));assert(!beamHits({...p,angle:0},e,[]));assert(!beamHits(p,{...e,x:12},[]));assert(!beamHits(p,e,[{x:2,z:0,w:1,d:3}]));assert(visible(p,{x:5,z:4},[{x:2,z:0,w:1,d:1}]));});
test('movement, diagonal normalization and swept dash collision',()=>{const g=new Game();g.enemies=[];const before={...g.player};advance(g,1,{x:1,z:1});assert(distance(before,g.player)<4.75);const b={x:0,z:0,r:.4};moveBody(b,10,0,[{x:2,z:0,w:.2,d:5}]);assert(b.x<1.6);assert(!blocked(g.player.x,g.player.z,g.player.r,g.obstacles));});
test('battery exhaustion has recovery hysteresis and items are bounded',()=>{const g=new Game();g.enemies=[];advance(g,9,{light:true});assert(g.exhausted);assert(g.player.battery>0);advance(g,2,{light:false});assert(!g.exhausted);assert(g.player.battery<=100);g.player.battery=10;assert(g.consume('cell'));assert.equal(g.player.cells,1);g.player.hp=2;assert(g.consume('heal'));assert.equal(g.player.hp,4);assert.equal(g.player.heal,1);});
test('beam damage kills once, knockback immunity protects dash, death stops simulation',()=>{const g=new Game();g.obstacles=[];Object.assign(g.player,{x:0,z:0,angle:0});g.enemies=[{...g.enemies[0],x:g.player.x,z:g.player.z+3,state:'hunt',speed:0}];advance(g,2,{light:true});assert.equal(g.kills,1);const p=g.player;p.invulnerable=0;g.dash(1,0);g.hit(1,{x:p.x-1,z:p.z});assert.equal(p.hp,5);p.invulnerable=0;g.hit(5,{x:p.x-1,z:p.z});assert.equal(g.status,'dead');const time=g.time;advance(g,1,{});assert.equal(g.time,time);});
test('the key can be picked up unlit from the start and escape requires no kills', () => {
  for (const stage of [0, 1, 98, 997, 998]) {
    const g = new Game(stage);
    assert(g.keyAvailable);
    assert(!g.keyVisibleOnMap);
    Object.assign(g.player, g.config.exit);
    g.tick(1/60, {});
    assert.equal(g.status, 'playing', 'exit stays locked without the key');
    Object.assign(g.player, g.config.key);
    g.tick(1/60, {});
    assert(g.hasKey);
    assert(!g.keyVisibleOnMap, 'collected keys leave the map');
    Object.assign(g.player, g.config.exit);
    g.tick(1/60, {});
    assert.equal(g.status, 'clear');
    assert.equal(g.kills, 0);
    assert(g.enemies.every(e => e.hp === e.maxHp));
    assert.equal(g.events.filter(e => e.type === 'clear').length, 1);
    g.tick(1/60, {});
    assert.equal(g.events.filter(e => e.type === 'clear').length, 1);
  }
});

test('the minimap remembers a key only after an unobstructed beam reaches it', () => {
  const g = new Game();
  g.enemies = [];
  g.obstacles = [];
  Object.assign(g.player, {x:0, z:0, angle:0});
  g.config.key = {x:0, z:5};
  g.tick(1/60, {});
  assert(!g.keyVisibleOnMap, 'proximity without light does not reveal it');
  g.player.angle = Math.PI;
  g.tick(1/60, {light:true, aim:Math.PI});
  assert(!g.keyVisibleOnMap, 'the light must face the key');
  g.player.angle = 0;
  g.obstacles = [{x:0, z:2, w:3, d:1}];
  g.tick(1/60, {light:true, aim:0});
  assert(!g.keyVisibleOnMap, 'walls block discovery');
  g.obstacles = [];
  g.config.key.z = 14;
  g.tick(1/60, {light:true, aim:0});
  assert(!g.keyVisibleOnMap, 'the key must be in range');
  g.config.key.z = 5;
  g.tick(1/60, {light:true, aim:0});
  assert(g.keyVisibleOnMap);
  assert(!g.hasKey, 'revealing does not collect it');
  g.player.angle = Math.PI;
  g.tick(1/60, {});
  assert(g.keyVisibleOnMap, 'discovery survives switching the light off');
  assert.equal(g.events.filter(e => e.type === 'keyReveal').length, 1);
  Object.assign(g.player, g.config.key);
  g.tick(1/60, {});
  assert(g.hasKey);
  assert(!g.keyVisibleOnMap);
});
test('brute telegraphs before its charge and recovers afterwards',()=>{const g=new Game();g.obstacles=[];const e={...g.enemies.at(-1),x:5,z:10,state:'hunt',cooldown:0};g.enemies=[e];g.player.x=1;g.player.z=10;g.tick(1/60,{});assert.equal(e.state,'windup');advance(g,.5,{});assert.equal(e.state,'windup');advance(g,.7,{});assert.equal(e.state,'charge');advance(g,.8,{});assert.equal(e.state,'recover');});
