import {rng,clamp} from './core.js';
import {CAMERA_ZOOM} from './world.js';
// Same simulation and controls, rendered without a GPU when WebGL is unavailable.
export class CanvasView {
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');if(!this.ctx)throw Error('Canvas is unavailable');this.effects=[];this.camX=1;this.camZ=8;this.resize();window.addEventListener('resize',()=>this.resize());window.visualViewport?.addEventListener('resize',()=>this.resize());}
 resize(){this.w=innerWidth;this.h=innerHeight;const d=Math.min(devicePixelRatio,1.5);this.canvas.width=Math.round(this.w*d);this.canvas.height=Math.round(this.h*d);this.ctx.setTransform(d,0,0,d,0,0);this.scale=this.h*CAMERA_ZOOM/(innerWidth>innerHeight?23:29);}
 build(game){this.game=game;this.effects=[];this.camX=game.player.x;this.camZ=game.player.z;this.bg=document.createElement('canvas');this.bg.width=2200;this.bg.height=2300;const c=this.bg.getContext('2d'),r=rng(game.config.seed),theme=game.config.theme;c.fillStyle=theme.floor;c.fillRect(0,0,2200,2300);for(let i=0;i<34000;i++){c.fillStyle=i%3?'#9aab8b0a':'#06192016';c.fillRect(r()*2200,r()*2300,r()*4+1,r()*4+1);}c.save();c.translate(1100,1150);c.scale(40,40*.8);
 for(const room of game.config.rooms){c.fillStyle=theme.room;c.fillRect(room.x-room.w/2,room.z-room.d/2,room.w,room.d);c.strokeStyle='#13282e55';c.lineWidth=.03;for(let z=room.z-room.d/2;z<room.z+room.d/2;z++){c.beginPath();c.moveTo(room.x-room.w/2,z);c.lineTo(room.x+room.w/2,z);c.stroke();}for(let x=room.x-room.w/2;x<room.x+room.w/2;x++){c.beginPath();c.moveTo(x,room.z-room.d/2);c.lineTo(x,room.z+room.d/2);c.stroke();}}
 for(let i=0;i<90;i++){const x=(r()-.5)*37,z=(r()-.5)*41;c.strokeStyle='#122a2d65';c.lineWidth=.025;c.beginPath();c.moveTo(x,z);c.lineTo(x+.7,z+.3);c.lineTo(x+.5,z+1);c.stroke();}
 for(const o of game.obstacles){c.fillStyle='#030d1666';c.fillRect(o.x-o.w/2+.1,o.z-o.d/2+.1,o.w,o.d+.32);if(o.kind==='wall'){c.fillStyle=theme.wall;c.fillRect(o.x-o.w/2,o.z-o.d/2,o.w,o.d);c.fillStyle=theme.cap;c.fillRect(o.x-o.w/2,o.z-o.d/2-.14,o.w,o.d-.04);c.strokeStyle='#152b3377';c.lineWidth=.055;c.strokeRect(o.x-o.w/2,o.z-o.d/2-.14,o.w,o.d-.04);}else if(o.kind==='car')this.car(c,o);else this.crate(c,o);}
 const colors=['#2a4436','#35543b','#3d6144','#23463b'];for(const room of game.config.rooms){for(let i=0;i<(game.stage%5===2?15:4);i++){const x=room.x+(r()-.5)*(room.w-1),z=room.z+(r()-.5)*(room.d-1),size=.1+r()*.16;c.fillStyle=colors[i%4];c.beginPath();c.ellipse(x,z,size,size*.5,r()*3,0,Math.PI*2);c.fill();}}
 c.fillStyle='#b8b2c080';c.font='bold .7px sans-serif';c.textAlign='center';c.fillText('STAY IN LIGHT',game.config.start.x,game.config.start.z-1.3);
 for(const {x,z}of game.config.lamps){const g=c.createRadialGradient(x,z,0,x,z,2.6);g.addColorStop(0,'#ffc57d47');g.addColorStop(.4,'#e4ad6724');g.addColorStop(1,'#e4ad6700');c.fillStyle=g;c.beginPath();c.arc(x,z,2.6,0,Math.PI*2);c.fill();c.fillStyle='#18303a';c.fillRect(x-.06,z-1.6,.12,1.6);c.fillRect(x-.06,z-1.6,.6,.1);c.fillStyle='#ffe4a5';c.beginPath();c.ellipse(x+.5,z-1.42,.2,.14,0,0,Math.PI*2);c.fill();}
 c.restore();}
 fence(c,x1,z1,x2,z2){const d=Math.hypot(x2-x1,z2-z1);c.strokeStyle='#71858988';c.lineWidth=.035;c.beginPath();c.moveTo(x1,z1);c.lineTo(x2,z2);c.moveTo(x1,z1-.8);c.lineTo(x2,z2-.8);c.stroke();for(let k=0;k<d;k+=.45){const x=x1+(x2-x1)*k/d,z=z1+(z2-z1)*k/d;c.beginPath();c.moveTo(x,z);c.lineTo(x+.35,z-.8);c.moveTo(x,z-.8);c.lineTo(x+.35,z);c.stroke();}for(let k=0;k<d;k+=2.5){const x=x1+(x2-x1)*k/d,z=z1+(z2-z1)*k/d;c.strokeStyle='#718b8f';c.lineWidth=.12;c.beginPath();c.moveTo(x,z+.2);c.lineTo(x,z-1.1);c.stroke();}}
 crate(c,o){const {x,z,w,d}=o;c.fillStyle='#5a4938';c.fillRect(x-w/2,z-d/2,w,d);c.fillStyle='#7e684a';c.fillRect(x-w/2,z-d/2-.2,w,d-.2);c.strokeStyle='#ad9164';c.lineWidth=.1;c.strokeRect(x-w/2+.1,z-d/2-.1,w-.2,d-.4);c.beginPath();c.moveTo(x-w/2+.12,z-d/2-.1);c.lineTo(x+w/2-.12,z+d/2-.5);c.stroke();c.strokeStyle='#403b31';c.lineWidth=.03;for(let k=-w/2+.4;k<w/2;k+=.3){c.beginPath();c.moveTo(x+k,z-d/2);c.lineTo(x+k,z+d/2-.4);c.stroke();}}
 car(c,o){const {x,z,w,d}=o;c.save();c.translate(x,z);c.fillStyle='#0b1722';for(const sx of [-1,1])for(const sz of [-1,1])c.fillRect(sx*w*.32-.25,sz*d*.49-.2,.5,.4);c.fillStyle='#34566c';this.round(c,-w/2,-d/2,w,d,.3);c.fillStyle='#527084';this.round(c,-w/2+.1,-d/2-.15,w-.2,d-.15,.24);c.fillStyle='#16323e';this.round(c,-.8,-d/2,.3,d-.4,.06);this.round(c,.55,-d/2,.35,d-.4,.06);c.fillStyle='#354d60';this.round(c,-.46,-d/2-.12,.93,d-.15,.12);c.strokeStyle='#889587';c.lineWidth=.055;c.strokeRect(-w/2+.2,-d/2+.1,w-.4,d-.55);c.fillStyle='#f2d79c';for(const sz of [-.63,.43])c.fillRect(w/2-.1,sz,.1,.25);c.fillStyle='#ad5d51';for(const sz of [-.63,.43])c.fillRect(-w/2-.01,sz,.1,.25);c.restore();}
 round(c,x,y,w,h,r){c.beginPath();c.roundRect(x,y,w,h,r);c.fill();}
 pos(x,z,y=0){return {x:this.w/2+(x-this.camX)*this.scale,y:this.h*.52+(z-this.camZ)*this.scale*.8-y*this.scale};}
 shadow(x,z,r){const c=this.ctx,a=this.pos(x,z);c.fillStyle='#010c176d';c.beginPath();c.ellipse(a.x,a.y+this.scale*.17,r*this.scale,r*this.scale*.48,0,0,Math.PI*2);c.fill();}
 halo(x,y,r,color='#ffce72'){const c=this.ctx,g=c.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color+'b0');g.addColorStop(.25,color+'48');g.addColorStop(1,color+'00');c.fillStyle=g;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill();}
 actor(e,hero,t){const c=this.ctx,s=this.scale*(hero?1:e.type==='brute'?1.7:e.type==='skitter'?.73:1);this.shadow(e.x,e.z,hero?.62:e.r*1.3);const a=this.pos(e.x,e.z);c.save();c.translate(a.x,a.y);c.scale(s,s);const bob=Math.sin(t*(hero?7:5)+(e.phase||0))*.035;c.translate(0,bob);if(e.hp<=0){c.globalAlpha=clamp(1-e.death/.5,0,1);c.scale(Math.max(.01,1-e.death),Math.max(.01,1-e.death));}const facing=Math.sin(e.angle),fz=Math.cos(e.angle),body=hero?'#324b62':e.exposure>.1?'#455c5c':e.type==='brute'?'#444d50':'#1b2c39';c.fillStyle='#0b1925';for(const x of [-.2,.2]){c.beginPath();c.ellipse(x,.05,.17,.19,0,0,Math.PI*2);c.fill();}c.fillStyle=body;c.beginPath();c.ellipse(0,-.37,.38,.43,0,0,Math.PI*2);c.fill();c.strokeStyle=hero?'#476179':body;c.lineWidth=.21;c.lineCap='round';c.beginPath();c.moveTo(-.3,-.53);c.lineTo(-.46,-.13);c.moveTo(.3,-.53);c.lineTo(.47,-.18);c.stroke();if(!hero){c.strokeStyle='#526569';c.lineWidth=.06;for(const x of [-.47,.47])for(let j=0;j<3;j++){c.beginPath();c.moveTo(x+(j-1)*.09,-.17);c.lineTo(x+(j-1)*.13,.02);c.stroke();}}
 c.fillStyle=hero?'#deb691':body;const hx=facing*.08,hy=-.86+fz*.03;c.beginPath();c.ellipse(hx,hy,.34,.33,0,0,Math.PI*2);c.fill();if(hero){c.fillStyle='#262f34';c.beginPath();c.ellipse(hx-.035,hy-.12,.36,.25,-.2,0,Math.PI*2);c.fill();c.fillStyle='#a88255';c.fillRect(-.28,-.68,.13,.49);c.fillStyle='#17212c';c.beginPath();c.arc(hx+.13,hy+.04,.025,0,Math.PI*2);c.fill();const lx=facing*.68+.18,lz=-.48+fz*.3;c.strokeStyle='#c6a681';c.lineWidth=.19;c.beginPath();c.moveTo(.23,-.5);c.lineTo(lx*.8,lz);c.stroke();c.strokeStyle='#253c4b';c.lineWidth=.19;c.beginPath();c.moveTo(lx-facing*.2,lz-fz*.1);c.lineTo(lx+facing*.25,lz+fz*.15);c.stroke();c.fillStyle='#ffefb8';c.beginPath();c.ellipse(lx+facing*.27,lz+fz*.16,.12,.1,-e.angle,0,Math.PI*2);c.fill();}else{for(const x of [-.14,.14]){c.fillStyle=e.state==='windup'?'#ff8467':'#ffedb0';c.shadowColor=c.fillStyle;c.shadowBlur=10;c.beginPath();c.ellipse(hx+x+facing*.06,hy+.07,.055,.09,-facing*.2,0,Math.PI*2);c.fill();}c.shadowBlur=0;if(e.type==='brute'){c.fillStyle='#7a8178';c.beginPath();c.ellipse(-.1,-1.1,.2,.085,-.2,0,Math.PI*2);c.fill();}}c.restore();if(e.state==='windup'){const a=this.pos(e.x,e.z);c.strokeStyle='#ff8169';c.lineWidth=2;c.beginPath();c.ellipse(a.x,a.y,this.scale*(e.r+.35),this.scale*(e.r+.35)*.7,0,0,Math.PI*2);c.stroke();}}
 beam(game){if(!game.lit)return;const c=this.ctx,p=game.player,o=this.pos(p.x,p.z,.47),points=[];for(let i=0;i<=50;i++){const a=p.angle+(i/50*2-1)*game.halfAngle,dx=Math.sin(a),dz=Math.cos(a);let d=game.range;for(const b of game.obstacles){let lo=0,hi=d;for(const[v,dir,min,max]of[[p.x,dx,b.x-b.w/2,b.x+b.w/2],[p.z,dz,b.z-b.d/2,b.z+b.d/2]]){if(Math.abs(dir)<1e-8){if(v<min||v>max){lo=d+1;break;}}else{const a=(min-v)/dir,b=(max-v)/dir;lo=Math.max(lo,Math.min(a,b));hi=Math.min(hi,Math.max(a,b));}}if(lo<=hi&&lo<d)d=Math.max(.01,lo);}points.push(this.pos(p.x+dx*d,p.z+dz*d));}c.save();c.beginPath();c.moveTo(o.x,o.y);points.forEach(a=>c.lineTo(a.x,a.y));c.closePath();const g=c.createRadialGradient(o.x,o.y,0,o.x,o.y,game.range*this.scale);g.addColorStop(0,'#fff3bcb0');g.addColorStop(.18,'#ffdb7d65');g.addColorStop(.65,'#eac67725');g.addColorStop(1,'#eac67700');c.fillStyle=g;c.globalCompositeOperation='screen';c.fill();c.restore();this.halo(o.x,o.y,this.scale*1.8,'#ffde8d');}
 burst(x,z,big){for(let i=0;i<(big?25:13);i++)this.effects.push({x,z,y:.5,vx:(Math.random()-.5)*6,vz:(Math.random()-.5)*6,vy:2+Math.random()*2,life:.7+Math.random()*.3});}
 render(game,dt,title){const p=game.player,t=game.time,f=1-Math.exp(-dt*5);this.camX+=((title?p.x-3:clamp(p.x,-16,16))-this.camX)*f;this.camZ+=((title?p.z:clamp(p.z,-18,18))-this.camZ)*f;const c=this.ctx;c.clearRect(0,0,this.w,this.h);c.fillStyle='#162a35';c.fillRect(0,0,this.w,this.h);const origin=this.pos(-27.5,-28.75);c.drawImage(this.bg,origin.x,origin.y,55*this.scale,57.5*this.scale*.8);const ep=this.pos(game.config.exit.x,game.config.exit.z);c.strokeStyle=game.hasKey?'#91e6c2':'#527d76';c.lineWidth=3;c.beginPath();c.ellipse(ep.x,ep.y,this.scale*1.5,this.scale*.8,0,0,Math.PI*2);c.stroke();c.fillStyle='#a2e2cb';c.textAlign='center';c.font=`bold ${this.scale*.48}px sans-serif`;c.fillText('EXIT →',ep.x,ep.y-this.scale*1.3);if(game.hasKey)this.halo(ep.x,ep.y,this.scale*2,'#82edc0');
 this.beam(game);for(const q of game.pickups){if(q.taken)continue;const a=this.pos(q.x,q.z,.3);this.halo(a.x,a.y,this.scale*.8,q.type==='heal'?'#f59382':'#ead387');c.fillStyle=q.type==='heal'?'#b85951':'#d4b570';c.fillRect(a.x-5,a.y-7,10,14);c.fillStyle='#fff1c8';c.font='bold 12px sans-serif';c.fillText(q.type==='heal'?'+':'−',a.x,a.y+4);}
 const actors=[...game.enemies.filter(e=>e.death<.5),{...p,hero:true}].sort((a,b)=>a.z-b.z);for(const e of actors){if(e.hero&&p.invulnerable>0&&p.hp<5&&Math.floor(t*13)%2)continue;this.actor(e,e.hero,t);}if(game.keyAvailable&&!game.hasKey){const a=this.pos(game.config.key.x,game.config.key.z,.7+Math.sin(t*3)*.15);this.halo(a.x,a.y,this.scale*1.5);c.strokeStyle='#ffdf82';c.lineWidth=3;c.beginPath();c.arc(a.x,a.y-7,5,0,Math.PI*2);c.moveTo(a.x,a.y-2);c.lineTo(a.x,a.y+11);c.lineTo(a.x+6,a.y+11);c.stroke();}
 for(let i=this.effects.length-1;i>=0;i--){const e=this.effects[i];e.life-=dt;if(e.life<=0){this.effects.splice(i,1);continue;}e.x+=e.vx*dt;e.z+=e.vz*dt;e.y+=e.vy*dt;e.vy-=dt*7;const a=this.pos(e.x,e.z,e.y);c.globalAlpha=e.life;c.fillStyle='#ffe5a5';c.fillRect(a.x-2,a.y-2,4,4);}c.globalAlpha=1;}
}
