export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export const angleDelta=(a,b)=>Math.atan2(Math.sin(a-b),Math.cos(a-b));
export const STAGES=[
 {name:'廃校の裏庭',sub:'THE SCHOOLYARD',count:12,key:{x:-14,z:-9},exit:{x:15,z:-18},start:{x:1,z:10},seed:74},
 {name:'忘れられた資材置き場',sub:'THE FORGOTTEN YARD',count:15,key:{x:13,z:-13},exit:{x:-15,z:-18},start:{x:0,z:13},seed:129},
 {name:'夜明け前の中庭',sub:'BEFORE THE DAWN',count:16,key:{x:-14,z:-14},exit:{x:0,z:-19},start:{x:1,z:13},seed:501}
];
export function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
export function layout(index){
 const o=[{x:-17.5,z:-4,w:.7,d:23,kind:'wall'},{x:-11,z:-15.5,w:13.5,d:.7,kind:'wall'},{x:-4.5,z:-9,w:.6,d:13,kind:'wall'},{x:-4.5,z:4,w:.6,d:5,kind:'wall'}, {x:-11,z:6.5,w:13,d:.6,kind:'wall'}];
 const extra=index===1?[[7,5,4,2,'car'],[10,-5,3,3,'crate'],[-11,11,3,2,'crate'],[3,-12,3,2,'crate']]:index===2?[[10,5,4,2,'car'],[-8,11,3,2,'crate'],[11,-8,2,2,'crate'],[2,-7,3,1.6,'planter']]:[[8,11,4,2,'car'],[-2,6,1.5,1.5,'crate'],[11,-6,2,2,'crate'],[-12,-3,2,2,'crate'],[2,-13,2,2,'crate']];
 return [...o,...extra.map(([x,z,w,d,kind])=>({x,z,w,d,kind}))];
}
export function blocked(x,z,r,obstacles){return Math.abs(x)>19-r||Math.abs(z)>21-r||obstacles.some(o=>Math.abs(x-o.x)<o.w/2+r&&Math.abs(z-o.z)<o.d/2+r);}
export function moveBody(b,dx,dz,obs){const steps=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.18));for(let i=0;i<steps;i++){if(!blocked(b.x+dx/steps,b.z,b.r,obs))b.x+=dx/steps;if(!blocked(b.x,b.z+dz/steps,b.r,obs))b.z+=dz/steps;}}
export function visible(a,b,obs){const dx=b.x-a.x,dz=b.z-a.z;for(const o of obs){let lo=0,hi=1;for(const [v,d,min,max] of [[a.x,dx,o.x-o.w/2,o.x+o.w/2],[a.z,dz,o.z-o.d/2,o.z+o.d/2]]){if(Math.abs(d)<1e-8){if(v<min||v>max){lo=2;break;}}else{const t1=(min-v)/d,t2=(max-v)/d;lo=Math.max(lo,Math.min(t1,t2));hi=Math.min(hi,Math.max(t1,t2));}}if(lo<=hi&&lo<=1&&hi>=0)return false;}return true;}
export function beamHits(p,e,obs,range=9,halfAngle=.48){return distance(p,e)<range+e.r&&Math.abs(angleDelta(Math.atan2(e.x-p.x,e.z-p.z),p.angle))<halfAngle+e.r/Math.max(1,distance(p,e))&&visible(p,e,obs);}
export class Game {
 constructor(stage=0,upgrades=[],score=0){this.upgrades=upgrades;this.score=score;this.stage=stage;this.config=STAGES[stage];this.obstacles=layout(stage);this.time=0;this.status='playing';this.kills=0;this.events=[];this.hasKey=false;this.keyAvailable=false;this.lit=false;this.exhausted=false;this.flash=0;this.player={...this.config.start,r:.43,hp:5,maxHp:5,battery:100,angle:2.5,invulnerable:1.4,dashTime:0,dashCd:0,heal:2,cells:2,dx:0,dz:0};this.range=upgrades.includes('range')?11.5:9;this.damage=upgrades.includes('power')?42:31;this.halfAngle=upgrades.includes('wide')?.69:.48;this.enemies=[];this.pickups=[];this.rand=rng(this.config.seed);this.buildEnemies();this.buildNav();this.navTimer=0;this.navTarget='';}
 buildEnemies(){const locations=[[3,2],[7,-2],[13,3],[-1,-6],[8,-11],[-12,1],[-13,-9],[14,-14],[0,-17],[-10,12],[14,13],[-11,-13],[-1,17],[10,-17],[-14,17],[4,-9]];for(let i=0;i<this.config.count;i++){let [x,z]=locations[i];const boss=i===this.config.count-1,type=boss?'brute':i%4===2?'skitter':'shadow';const r=boss?.88:type==='skitter'?.35:.46;while(blocked(x,z,Math.max(r,.8),this.obstacles)){x+=.5;z+=.5;}const hp=boss?175+this.stage*55:type==='skitter'?30:43;this.enemies.push({id:i,x,z,r,type,hp,maxHp:hp,speed:boss?1.23:type==='skitter'?2.55:1.55,angle:0,state:'idle',timer:0,cooldown:0,exposure:0,phase:this.rand()*6.28,chargeX:0,chargeZ:0,death:0});}this.pickups.push({x:-12,z:12,type:'cell',taken:false},{x:13,z:0,type:'heal',taken:false});}
 buildNav(){this.navW=39;this.navD=43;this.walkable=new Uint8Array(this.navW*this.navD);for(let z=0;z<this.navD;z++)for(let x=0;x<this.navW;x++)this.walkable[z*this.navW+x]=blocked(x-19,z-21,.55,this.obstacles)?0:1;this.flow=new Int16Array(this.walkable.length);}
 updateNav(){const px=clamp(Math.round(this.player.x+19),0,38),pz=clamp(Math.round(this.player.z+21),0,42);let start=pz*this.navW+px;if(!this.walkable[start]){let best=Infinity;for(let i=0;i<this.walkable.length;i++)if(this.walkable[i]){const d=Math.hypot(i%39-px,Math.floor(i/39)-pz);if(d<best){start=i;best=d;}}}this.flow.fill(-1);this.flow[start]=0;const queue=[start];for(let q=0;q<queue.length;q++){const i=queue[q],x=i%39,z=Math.floor(i/39);for(const [dx,dz]of[[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,nz=z+dz,ni=nz*39+nx;if(nx<0||nx>=39||nz<0||nz>=43||!this.walkable[ni]||this.flow[ni]>=0)continue;this.flow[ni]=this.flow[i]+1;queue.push(ni);}}}
 direction(e){const p=this.player;if(visible(e,p,this.obstacles))return{x:p.x-e.x,z:p.z-e.z};const cx=clamp(Math.round(e.x+19),0,38),cz=clamp(Math.round(e.z+21),0,42);let target=null,best=Infinity;for(let dz=-1;dz<=1;dz++)for(let dx=-1;dx<=1;dx++){const x=cx+dx,z=cz+dz,i=z*39+x;if(x<0||x>=39||z<0||z>=43||this.flow[i]<0)continue;const point={x:x-19,z:z-21};if(!visible(e,point,this.obstacles))continue;const score=this.flow[i]+Math.hypot(point.x-e.x,point.z-e.z)*.1;if(score<best){best=score;target=point;}}return target?{x:target.x-e.x,z:target.z-e.z}:{x:0,z:0};}
 emit(type,data={}){this.events.push({type,...data});}
 consume(type){if(this.status!=='playing')return false;const p=this.player;if(type==='heal'&&p.heal>0&&p.hp<p.maxHp){p.heal--;p.hp=Math.min(p.maxHp,p.hp+2);this.emit('heal');return true;}if(type==='cell'&&p.cells>0&&p.battery<95){p.cells--;p.battery=Math.min(100,p.battery+70);this.exhausted=false;this.emit('cell');return true;}return false;}
 dash(mx,mz){const p=this.player;if(this.status!=='playing'||p.dashCd>0)return;let d=Math.hypot(mx,mz);p.dx=d>.1?mx/d:Math.sin(p.angle);p.dz=d>.1?mz/d:Math.cos(p.angle);p.dashTime=.22;p.dashCd=this.upgrades.includes('dash')?.85:1.3;p.invulnerable=Math.max(p.invulnerable,.35);this.emit('dash',{x:p.x,z:p.z});}
 hit(dmg,e){const p=this.player;if(p.invulnerable>0)return;p.hp=Math.max(0,p.hp-dmg);p.invulnerable=1.25;this.flash=.3;const d=Math.max(.1,distance(p,e));moveBody(p,(p.x-e.x)/d*.65,(p.z-e.z)/d*.65,this.obstacles);this.emit('hurt');if(p.hp<=0){this.status='dead';this.emit('dead');}}
 tick(dt,input={}){if(this.status!=='playing')return;dt=Math.min(dt,1/30);this.time+=dt;const p=this.player;this.flash=Math.max(0,this.flash-dt);p.invulnerable=Math.max(0,p.invulnerable-dt);p.dashCd=Math.max(0,p.dashCd-dt);let mx=input.x||0,mz=input.z||0;const md=Math.hypot(mx,mz);if(md>1){mx/=md;mz/=md;}if(input.dash)this.dash(mx,mz);
 this.lit=!!input.light&&!this.exhausted&&p.battery>0;if(this.lit){p.battery=Math.max(0,p.battery-dt*(this.upgrades.includes('battery')?8.5:12));if(p.battery<=0){this.exhausted=true;this.lit=false;this.emit('empty');}}else{p.battery=Math.min(100,p.battery+dt*16);if(this.exhausted&&p.battery>=28)this.exhausted=false;}
 if(p.dashTime>0){p.dashTime-=dt;moveBody(p,p.dx*dt*16,p.dz*dt*16,this.obstacles);}else moveBody(p,mx*dt*(this.lit?3.5:4.6),mz*dt*(this.lit?3.5:4.6),this.obstacles);
 let aim=input.aim;if(aim==null&&this.lit){let best=Infinity,target;for(const e of this.enemies){if(e.hp<=0)continue;const d=distance(e,p);if(d<this.range+2&&d<best&&visible(p,e,this.obstacles)){best=d;target=e;}}if(target)aim=Math.atan2(target.x-p.x,target.z-p.z);}if(aim==null&&md>.12)aim=Math.atan2(mx,mz);if(aim!=null)p.angle+=angleDelta(aim,p.angle)*Math.min(1,dt*12);
 this.navTimer-=dt;if(this.navTimer<=0){this.navTimer=.45;this.updateNav();}
 for(const e of this.enemies){if(e.hp<=0){e.death+=dt;continue;}e.cooldown=Math.max(0,e.cooldown-dt);const d=distance(e,p),lit=this.lit&&beamHits(p,e,this.obstacles,this.range,this.halfAngle);e.exposure=clamp(e.exposure+(lit?dt*4:-dt*3),0,1);if(lit){e.hp-=this.damage*dt*(e.state==='windup'?.75:1);if(e.hp<=0){this.kills++;this.score+=e.type==='brute'?500:100;this.emit('kill',{x:e.x,z:e.z,brute:e.type==='brute'});if(e.type==='brute')this.emit('bruteDown');if(this.kills%4===0)this.pickups.push({x:e.x,z:e.z,type:'energy',taken:false});continue;}}
 if(e.state==='idle'){e.angle+=dt*.3;if(d<11.5||(this.kills>=this.config.count-3)){e.state='hunt';this.emit('alert',{brute:e.type==='brute'});}else continue;}
 if(e.state==='windup'){e.timer-=dt;if(e.timer<=0){e.state='charge';e.timer=e.type==='brute'?.68:.25;}continue;}
 if(e.state==='charge'){e.timer-=dt;moveBody(e,e.chargeX*dt*(e.type==='brute'?10:7),e.chargeZ*dt*(e.type==='brute'?10:7),this.obstacles);if(distance(e,p)<e.r+p.r+.16)this.hit(1,e);if(e.timer<=0){e.state='recover';e.timer=e.type==='brute'?1.2:.7;}continue;}
 if(e.state==='recover'){e.timer-=dt;if(e.timer<=0){e.state='hunt';e.cooldown=1.1;}continue;}
 if(d<(e.type==='brute'?5.1:1.5)&&e.cooldown<=0&&visible(e,p,this.obstacles)){e.state='windup';e.timer=e.type==='brute'?1.05:.6;e.chargeX=(p.x-e.x)/Math.max(.01,d);e.chargeZ=(p.z-e.z)/Math.max(.01,d);e.angle=Math.atan2(e.chargeX,e.chargeZ);this.emit('windup',{brute:e.type==='brute'});continue;}
 const dir=this.direction(e),len=Math.hypot(dir.x,dir.z);if(len>.01){const s=e.speed*(lit?.32:1);e.angle=Math.atan2(dir.x,dir.z);moveBody(e,dir.x/len*s*dt,dir.z/len*s*dt,this.obstacles);if(lit&&d<3.4)moveBody(e,-dir.x/len*dt*.75,-dir.z/len*dt*.75,this.obstacles);}
 }
 // Resolve overlap so a group remains readable and cannot occupy a single attack point.
 for(let i=0;i<this.enemies.length;i++){const a=this.enemies[i];if(a.hp<=0)continue;for(let j=i+1;j<this.enemies.length;j++){const b=this.enemies[j];if(b.hp<=0)continue;const d=distance(a,b),overlap=a.r+b.r+.15-d;if(overlap>0){const ax=d>.001?(a.x-b.x)/d:1,az=d>.001?(a.z-b.z)/d:0;moveBody(a,ax*overlap*.25,az*overlap*.25,this.obstacles);moveBody(b,-ax*overlap*.25,-az*overlap*.25,this.obstacles);}}}
 if(this.kills===this.config.count&&!this.keyAvailable){this.keyAvailable=true;this.emit('keyReveal');}if(this.keyAvailable&&!this.hasKey&&distance(p,this.config.key)<1.4){this.hasKey=true;this.score+=250;this.emit('key');}for(const q of this.pickups){if(!q.taken&&distance(p,q)<1.05){if(q.type==='energy'){p.battery=Math.min(100,p.battery+32);q.taken=true;}else if(q.type==='cell'&&p.cells<5){p.cells++;q.taken=true;}else if(q.type==='heal'&&p.heal<5){p.heal++;q.taken=true;}if(q.taken)this.emit('pickup',{item:q.type});}}
 if(this.status==='playing'&&this.hasKey&&distance(p,this.config.exit)<1.65){this.status='clear';this.score+=p.hp*100+Math.max(0,Math.round(350-this.time));this.emit('clear');}}
}
