export class Input{
 constructor(){this.keys=new Set();this.x=0;this.z=0;this.light=false;this.aim=null;this.dash=false;this.moveId=null;this.aimId=null;this.onAction=()=>{};const move=document.querySelector('#move'),knob=document.querySelector('#knob'),light=document.querySelector('#light');
 const update=e=>{const r=move.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,max=r.width*.32,d=Math.hypot(dx,dy),s=d>max?max/d:1;this.x=dx*s/max;this.z=dy*s/max;knob.style.transform=`translate(${dx*s}px,${dy*s}px)`;};
 move.addEventListener('pointerdown',e=>{if(this.moveId!==null)return;this.moveId=e.pointerId;move.setPointerCapture(e.pointerId);update(e);e.preventDefault();});move.addEventListener('pointermove',e=>{if(e.pointerId===this.moveId)update(e);});const end=e=>{if(e.pointerId!==this.moveId)return;this.moveId=null;this.x=this.z=0;knob.style.transform='';};for(const t of ['pointerup','pointercancel','lostpointercapture'])move.addEventListener(t,end);
 light.addEventListener('pointerdown',e=>{this.aimId=e.pointerId;this.aimStart={x:e.clientX,y:e.clientY};this.dragged=false;light.setPointerCapture(e.pointerId);e.preventDefault();});light.addEventListener('pointermove',e=>{if(e.pointerId!==this.aimId)return;const dx=e.clientX-this.aimStart.x,dy=e.clientY-this.aimStart.y;if(Math.hypot(dx,dy)>13){this.dragged=true;this.light=true;this.aim=Math.atan2(dx,dy);}});light.addEventListener('pointerup',e=>{if(e.pointerId!==this.aimId)return;if(!this.dragged)this.light=!this.light;this.aim=null;this.aimId=null;});light.addEventListener('pointercancel',()=>{this.aim=null;this.aimId=null;});light.addEventListener('click',e=>{if(e.detail===0)this.light=!this.light;});
 document.querySelector('#dash').addEventListener('pointerdown',e=>{this.dash=true;e.preventDefault();});document.querySelector('#dash').addEventListener('click',e=>{if(e.detail===0)this.dash=true;});
 window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();this.keys.add(e.code);if(e.repeat)return;if(e.code==='KeyF')this.light=!this.light;if(e.code==='ShiftLeft'||e.code==='ShiftRight')this.dash=true;if(e.code==='Escape')this.onAction('pause');if(e.code==='KeyQ')this.onAction('heal');if(e.code==='KeyE')this.onAction('cell');});window.addEventListener('keyup',e=>this.keys.delete(e.code));window.addEventListener('blur',()=>this.reset());document.addEventListener('visibilitychange',()=>{if(document.hidden)this.reset();});document.addEventListener('contextmenu',e=>e.preventDefault());for(const name of ['gesturestart','gesturechange','gestureend'])document.addEventListener(name,e=>e.preventDefault(),{passive:false});document.addEventListener('touchmove',e=>{if(!e.target.closest('.modal-card'))e.preventDefault();},{passive:false});
 }
 read(){const x=this.x+(this.keys.has('KeyD')||this.keys.has('ArrowRight')?1:0)-(this.keys.has('KeyA')||this.keys.has('ArrowLeft')?1:0),z=this.z+(this.keys.has('KeyS')||this.keys.has('ArrowDown')?1:0)-(this.keys.has('KeyW')||this.keys.has('ArrowUp')?1:0);const v={x,z,aim:this.aim,light:this.light||this.keys.has('Space'),dash:this.dash};this.dash=false;return v;}
 reset(){this.keys.clear();this.x=this.z=0;this.light=false;this.aim=null;this.dash=false;this.moveId=this.aimId=null;document.querySelector('#knob').style.transform='';}
}
