import {Game,STAGES,clamp} from './core.js';
import {View} from './scene.js';
import {CanvasView} from './canvas-view.js';
import {Input} from './input.js';
import {Audio} from './audio.js';
import {renderAreaClear} from './clear-screen.js';
const $=s=>document.querySelector(s), SAVE='light-game-save-v1';
let view,game,input,sound,mode='title',returnMode='playing',last=performance.now(),acc=0,toastTimer=0,hudTimer=0,upgrades=[],lastHit=0;
const safeRead=()=>{try{const s=JSON.parse(localStorage.getItem(SAVE));return s&&Number.isInteger(s.stage)&&s.stage>=0&&s.stage<3&&Array.isArray(s.upgrades)&&s.upgrades.every(v=>['power','range','wide','battery','dash'].includes(v))&&Number.isFinite(s.score)?s:null;}catch{return null;}};
function save(stage){try{localStorage.setItem(SAVE,JSON.stringify({stage,upgrades,score:game.score}));}catch{}}
function clearSave(){try{localStorage.removeItem(SAVE);}catch{}}
function toast(text,time=3){$('#toast').textContent=text;$('#toast').style.opacity=1;toastTimer=time;}
function modal(eye,heading,body,actions,layout=''){const panel=$('#modal');panel.classList.toggle('stage-clear',layout==='stage-clear');panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-labelledby','modal-heading');$('#modal-body').scrollTop=0;$('#modal-eyebrow').textContent=eye;$('#modal-heading').textContent=heading;$('#modal-body').innerHTML=body;$('#modal-actions').replaceChildren();for(const [label,fn]of actions){const b=document.createElement('button');b.type='button';b.innerHTML=label;b.onclick=fn;$('#modal-actions').append(b);}$('#modal').hidden=false;}
function closeModal(){$('#modal').hidden=true;}
function start(stage=0,score=0){input.reset();game=new Game(stage,upgrades,score);view.build(game);mode='playing';$('#title').hidden=true;$('#hud').hidden=false;closeModal();save(stage);sound.start();last=performance.now();acc=0;toast(stage===0?'「てらす」をタップ。光で影を追い払おう。':'エリア '+(stage+1)+' — '+STAGES[stage].name,4);updateHUD();}
function newGame(){upgrades=[];start();}
function title(){mode='title';input.reset();$('#hud').hidden=true;$('#title').hidden=false;closeModal();game=new Game();game.player.x=5;game.player.z=8;game.player.angle=2.23;game.lit=true;view.build(game);$('#continue').hidden=!safeRead();}
function pause(){if(mode==='playing'){mode='paused';input.reset();modal('TAKE A BREATH','ひとやすみ',`<p>光を消している間は電池が自動回復。<br>敵が赤く光ったら、ダッシュで横にかわそう。</p>`,[['探索にもどる',resume],['あそびかた',()=>help('paused')],['タイトルへ',title]]);}else if(mode==='paused')resume();}
function resume(){mode='playing';closeModal();last=performance.now();acc=0;}
function help(back='title'){returnMode=back;if(mode==='playing'||mode==='paused'){mode='paused';input.reset();}modal('HOW TO PLAY','光を、味方に。',`<p><strong>① 左スティックで移動</strong><br>周りを探し、影の敵を見つけよう。</p><p><strong>②「てらす」をタップで ON / OFF</strong><br>近くの敵を自動で狙います。ボタンをドラッグすると、その方向を狙えます。消灯すると電池が回復。</p><p><strong>③ 赤い予告を見たら「ダッシュ」</strong><br>回避中は無敵。大型の敵の突進には特に注意！</p><p><strong>④ 全ての敵を倒す → 鍵を取る → EXIT</strong><br>3エリアを進み、最後の番人を倒して脱出しよう。</p><p>PC：WASD / 矢印で移動 · Fで点灯切替<br>Spaceで照射 · Shiftで回避 · Qで回復 · Eで電池</p>`,[['わかった',()=>{closeModal();if(returnMode==='paused')pauseMenu();}]]);}
function pauseMenu(){mode='playing';pause();}
function clear(){mode='clear';input.reset();const stage=game.stage;const body=`<p>${STAGES[stage].name}に、静けさが戻った。</p><div class="score-row"><span>退治した影</span><strong>${game.kills} / ${game.config.count}</strong></div><div class="score-row"><span>探索時間</span><strong>${Math.floor(game.time/60)}:${String(Math.floor(game.time%60)).padStart(2,'0')}</strong></div><div class="score-row"><span>トータルスコア</span><strong>${game.score.toLocaleString()}</strong></div>`;if(stage===2){clearSave();modal('ALL AREAS CLEAR','夜を、抜け出した。',body+'<p>懐中電灯の小さな光が、朝まできみを守った。<br>おつかれさま。また次の夜に。</p>',[['もう一度、夜の探索へ',newGame],['タイトルへ',title]]);}else{renderAreaClear(game,upgrades,{modal,onNext:next=>{upgrades=next.upgrades;start(next.stage,next.score);}});}}
function dead(){mode='dead';input.reset();modal('THE LIGHT WILL RETURN','もう一度、灯そう。',`<p>消灯で電池を回復しながら、敵との距離を保とう。<br>大型の敵は、突進を避けた直後がチャンス。</p><div class="score-row"><span>退治した影</span><strong>${game.kills} / ${game.config.count}</strong></div>`,[['このエリアをやり直す',()=>{const s=safeRead();start(game.stage,s?.score||0);}],['タイトルへ',title]]);}
function events(){for(const e of game.events){sound.play(e.type);if(e.type==='kill')view.burst(e.x,e.z,e.brute);if(e.type==='keyReveal')toast('影をすべて退治した！ ミニマップの鍵を探そう。',5);if(e.type==='key')toast('鍵を手に入れた！ 緑色の EXIT へ。',5);if(e.type==='empty')toast('電池を回復中… 距離をとろう。',2);if(e.type==='bruteDown')toast('影の番人を退治した！',3);if(e.type==='heal')toast('体力が回復した',1.5);if(e.type==='cell')toast('電池を補充した',1.5);if(e.type==='pickup')toast(e.item==='heal'?'回復キットを入手':e.item==='cell'?'予備電池を入手':'光のかけらで電池回復',1.4);if(e.type==='clear')clear();if(e.type==='dead')dead();}game.events.length=0;}
function updateHUD(){const p=game.player;$('#hearts').innerHTML=Array.from({length:p.maxHp},(_,i)=>`<span class="${i<p.hp?'':'empty'}">♥</span>`).join('');$('#hearts').setAttribute('aria-label',`体力 ${p.hp} / ${p.maxHp}`);$('#charge').style.width=p.battery+'%';$('#charge').style.background=game.exhausted?'#df7b61':'#f8d680';$('#charge-label').textContent=Math.ceil(p.battery)+'%';$('#kill-objective').textContent=`${game.keyAvailable?'✓':'◇'} すべての敵をたおそう  ${game.kills}/${game.config.count}`;$('#kill-objective').className=game.keyAvailable?'done':'';$('#key-objective').textContent=`${game.hasKey?'✓':'◇'} カギを見つけよう  ${game.hasKey?'1':'0'}/1`;$('#key-objective').className=game.hasKey?'done':'';$('#exit-objective').textContent=game.hasKey?'➜ 出口へ向かおう':'◇ 出口へ向かおう';$('#exit-objective').className=game.hasKey?'done':'';$('#area-number').textContent=`AREA 0${game.stage+1} / 03`;$('#area-name').textContent=game.config.name;$('#light').classList.toggle('on',game.lit);$('#light-state').textContent=game.exhausted?'回復中…':game.lit?'ON · 自動で狙う':'タップで ON';$('#dash').classList.toggle('cooldown',p.dashCd>0);$('#dash-state').textContent=p.dashCd>0?p.dashCd.toFixed(1)+' s':'READY';$('#heal b').textContent=p.heal;$('#cell b').textContent=p.cells;const boss=game.enemies.find(e=>e.type==='brute');$('#boss').hidden=!(boss&&boss.hp>0&&boss.state!=='idle');if(boss)$('#boss b').style.width=Math.max(0,boss.hp/boss.maxHp*100)+'%';drawMap();}
function drawMap(){const c=$('#map'),ctx=c.getContext('2d'),w=c.width,h=c.height,s=Math.min((w-22)/40,(h-20)/44),ox=w/2,oz=h/2;const at=(x,z)=>[ox+x*s,oz+z*s];ctx.clearRect(0,0,w,h);ctx.strokeStyle='#638182';ctx.lineWidth=1.5;ctx.strokeRect(ox-19*s,oz-21*s,38*s,42*s);ctx.fillStyle='#72858b55';for(const o of game.obstacles){const [x,z]=at(o.x-o.w/2,o.z-o.d/2);ctx.fillRect(x,z,o.w*s,o.d*s);}for(const e of game.enemies){if(e.hp<=0)continue;const [x,z]=at(e.x,e.z);ctx.fillStyle=e.type==='brute'?'#ef8f66':'#e36a6a';ctx.beginPath();ctx.arc(x,z,e.type==='brute'?3.7:2.7,0,Math.PI*2);ctx.fill();}let [x,z]=at(game.config.exit.x,game.config.exit.z);ctx.strokeStyle=game.hasKey?'#90ebc2':'#59786e';ctx.lineWidth=2;ctx.strokeRect(x-4,z-4,8,8);if(!game.hasKey){[x,z]=at(game.config.key.x,game.config.key.z);ctx.fillStyle=game.keyAvailable?'#ffe291':'#827850';ctx.font='bold 14px sans-serif';ctx.fillText('⚿',x-5,z+5);} [x,z]=at(game.player.x,game.player.z);ctx.save();ctx.translate(x,z);ctx.rotate(-game.player.angle);ctx.beginPath();ctx.moveTo(0,6);ctx.lineTo(-4,-4);ctx.lineTo(0,-2);ctx.lineTo(4,-4);ctx.closePath();ctx.fillStyle='#ffe6a5';ctx.fill();ctx.restore();}
function loop(now){requestAnimationFrame(loop);const dt=Math.min((now-last)/1000,.05);last=now;if(!game)return;if(mode==='playing'){acc+=dt;while(acc>=1/60){game.tick(1/60,input.read());events();acc-=1/60;if(mode!=='playing'){acc=0;break;}}sound.tick(dt,true);toastTimer-=dt;if(toastTimer<=0)$('#toast').style.opacity=0;hudTimer-=dt;if(hudTimer<=0){hudTimer=.08;updateHUD();}}else if(mode==='title'){game.time+=dt;game.lit=true;game.player.angle=2.23+Math.sin(game.time*.23)*.25;}
 $('#hit-flash').style.opacity=game.flash>0?Math.min(.65,game.flash*2):0;view.render(game,dt,mode==='title');}
try{try{view=new View($('#game'));}catch(webglError){console.info('WebGL unavailable; using compatible Canvas renderer.');const old=$('#game'),fresh=old.cloneNode(false);old.replaceWith(fresh);view=new CanvasView(fresh);}input=new Input();sound=new Audio();view.onContextLost=()=>{mode='paused';input.reset();modal('DISPLAY PAUSED','画面の再読み込みが必要です','<p>エリアの進行は保存されています。</p>',[['再読み込み',()=>location.reload()]]);};input.onAction=a=>{if(a==='pause')pause();else if(mode==='playing'){if(!game.consume(a))toast(a==='heal'?'体力満タン、またはキットがありません':'電池満タン、または予備電池がありません',1.5);}};$('#start').onclick=newGame;$('#continue').onclick=()=>{const s=safeRead();if(s){upgrades=s.upgrades;start(s.stage,s.score);}};$('#how').onclick=()=>help();$('#pause').onclick=pause;$('#sound').onclick=()=>$('#sound').textContent=sound.toggle()?'SOUND ON':'SOUND OFF';$('#heal').onclick=()=>input.onAction('heal');$('#cell').onclick=()=>input.onAction('cell');$('#portrait').onclick=()=>$('#rotate').classList.add('dismissed');document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='playing')pause();});window.addEventListener('blur',()=>{if(mode==='playing')pause();});title();$('#loading').hidden=true;requestAnimationFrame(loop);if('serviceWorker'in navigator&&location.hostname!=='localhost'&&location.hostname!=='127.0.0.1')navigator.serviceWorker.register('./sw.js').catch(()=>{});}catch(error){console.error(error);$('#loading').innerHTML='<strong>画面を準備できませんでした</strong><span>WebGL対応のSafari / Chromeで開いてください。</span><button onclick="location.reload()">もう一度読み込む</button>';}
