import * as T from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {rng,clamp} from './core.js';
import {CAMERA_ZOOM} from './world.js';
const V=T.Vector3;
export class View{
 constructor(canvas){this.renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance',alpha:false});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.2;this.scene=new T.Scene();this.scene.background=new T.Color('#122332');this.scene.fog=new T.FogExp2('#132733',.011);this.camera=new T.OrthographicCamera(-20,20,12,-12,.1,130);this.scene.add(new T.HemisphereLight(0x93b8db,0x32483d,2.1));const moon=new T.DirectionalLight(0x9cbcf9,2.4);moon.position.set(-15,28,-9);moon.castShadow=true;moon.shadow.mapSize.set(1024,1024);Object.assign(moon.shadow.camera,{left:-28,right:28,top:28,bottom:-28,near:1,far:80});moon.shadow.bias=-.001;moon.shadow.normalBias=.06;this.scene.add(moon);this.materials=new Map();this.effects=[];this.lamps=[];this.glowTexture=this.makeGlow();this.hero=this.makeHero();this.scene.add(this.hero);this.spot=new T.SpotLight(0xffe6a0,85,15,.54,.7,1.4);this.spot.target=new T.Object3D();this.scene.add(this.spot,this.spot.target);this.personal=new T.PointLight(0xffd995,10,5,1.3);this.scene.add(this.personal);this.cone=this.makeBeam();this.scene.add(this.cone);this.aimRing=this.ring(.6,0xffdf85,.3);this.scene.add(this.aimRing);this.resize();window.addEventListener('resize',()=>this.resize());window.visualViewport?.addEventListener('resize',()=>this.resize());canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.onContextLost?.();});this.width=innerWidth;this.camX=1;this.camZ=9;}
 mat(color,roughness=.9,emissive=0){const key=color+':'+roughness+':'+emissive;if(!this.materials.has(key))this.materials.set(key,new T.MeshStandardMaterial({color,roughness,metalness:roughness<.5?.4:0,emissive:color,emissiveIntensity:emissive,flatShading:true}));return this.materials.get(key);}
 mesh(g,color,parent,x=0,y=0,z=0){const m=new T.Mesh(g,typeof color==='object'?color:this.mat(color));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 box(p,x,y,z,w,h,d,c,rot=0){const m=this.mesh(new T.BoxGeometry(w,h,d),c,p,x,y,z);m.rotation.y=rot;return m;}
 ball(p,x,y,z,sx,sy,sz,c,detail=1){const m=this.mesh(new T.IcosahedronGeometry(1,detail),c,p,x,y,z);m.scale.set(sx,sy,sz);return m;}
 cylinder(p,x,y,z,r1,r2,h,c,n=10){return this.mesh(new T.CylinderGeometry(r1,r2,h,n),c,p,x,y,z);}
 makeGlow(){const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d'),g=ctx.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,'rgba(255,255,235,1)');g.addColorStop(.12,'rgba(255,240,180,.8)');g.addColorStop(.35,'rgba(255,205,100,.22)');g.addColorStop(1,'rgba(255,190,70,0)');ctx.fillStyle=g;ctx.fillRect(0,0,128,128);return new T.CanvasTexture(c);}
 glow(parent,x,y,z,size,color=0xffd88f,opacity=.75){const m=new T.Sprite(new T.SpriteMaterial({map:this.glowTexture,color,transparent:true,depthWrite:false,blending:T.AdditiveBlending,opacity}));m.position.set(x,y,z);m.scale.set(size,size,1);parent.add(m);return m;}
 ring(radius,color,opacity){const m=new T.Mesh(new T.RingGeometry(radius*.87,radius,40),new T.MeshBasicMaterial({color,transparent:true,opacity,depthWrite:false,side:T.DoubleSide}));m.rotation.x=-Math.PI/2;m.position.y=.045;return m;}
 text(text,w,h,color='#dfe8cf',bg='#17303a'){const c=document.createElement('canvas');c.width=512;c.height=256;const ctx=c.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,512,256);ctx.strokeStyle='#a3b3a680';ctx.lineWidth=8;ctx.strokeRect(10,10,492,236);ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=color;const lines=text.split('\n');ctx.font='bold '+(lines.length>1?62:70)+'px sans-serif';lines.forEach((s,i)=>ctx.fillText(s,256,128+(i-(lines.length-1)/2)*80));const map=new T.CanvasTexture(c);map.colorSpace=T.SRGBColorSpace;const m=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshStandardMaterial({map,roughness:1,side:T.DoubleSide}));return m;}
 floorTexture(seed,color='#3a4947'){const c=document.createElement('canvas');c.width=c.height=1024;const ctx=c.getContext('2d'),r=rng(seed);ctx.fillStyle=color;ctx.fillRect(0,0,1024,1024);for(let i=0;i<42000;i++){const x=r()*1024,y=r()*1024,s=r()*3+.5;ctx.fillStyle=r()>.5?'rgba(122,135,116,.14)':'rgba(15,25,25,.19)';ctx.fillRect(x,y,s,s);}for(let i=0;i<60;i++){ctx.strokeStyle='#1b292750';ctx.lineWidth=r()*2+1;ctx.beginPath();let x=r()*1024,y=r()*1024;ctx.moveTo(x,y);for(let j=0;j<5;j++){x+=r()*60-25;y+=r()*50-20;ctx.lineTo(x,y);}ctx.stroke();}const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(2,2);return t;}
 makeHero(){const root=new T.Group(),body=new T.Group();root.add(body);root.userData.body=body;this.ball(body,0,.83,0,.36,.43,.27,0x243447,2);this.box(body,0,.62,.04,.52,.18,.36,0x142330);this.ball(body,0,1.4,.03,.36,.4,.34,0xe4b189,2);this.ball(body,0,1.58,-.035,.385,.29,.355,0x282524,2);this.ball(body,.24,1.45,-.06,.14,.27,.26,0x262524);this.ball(body,-.26,1.48,-.05,.12,.25,.26,0x262524);this.ball(body,0,1.4,.345,.07,.08,.04,0xc9956e);for(const x of [-.15,.15])this.ball(body,x,1.48,.316,.025,.032,.025,0x101820);this.box(body,0,.95,-.32,.43,.5,.18,0x805d3a);this.box(body,0,1.12,-.43,.26,.1,.04,0xcea776);for(const x of [-.29,.29])this.box(body,x,.94,.19,.07,.52,.05,0xb5a083);this.heroLegs=[];for(const x of [-.18,.18]){const leg=new T.Group();leg.position.set(x,.55,0);body.add(leg);this.box(leg,0,-.15,0,.18,.42,.21,0x202630);this.ball(leg,0,-.43,.06,.14,.13,.24,0x121b22);this.heroLegs.push(leg);}this.ball(body,-.33,.88,.1,.13,.33,.14,0x293c4d);this.ball(body,.38,1.02,.2,.13,.14,.29,0x293c4d);this.ball(body,.38,1.03,.44,.12,.11,.13,0xd9a177);const flashlight=this.cylinder(body,.38,1.04,.61,.1,.12,.42,0x2a3136);flashlight.rotation.x=Math.PI/2;const rim=this.cylinder(body,.38,1.04,.86,.15,.12,.13,0xa69b72);rim.rotation.x=Math.PI/2;const lens=this.cylinder(body,.38,1.04,.933,.12,.12,.015,this.mat(0xffe9ac,.2,2));lens.rotation.x=Math.PI/2;this.heroGlow=this.glow(body,.38,1.04,.96,.85);root.add(this.shadow(.65));return root;}
 shadow(r){const s=new T.Mesh(new T.CircleGeometry(r,24),new T.MeshBasicMaterial({color:0x01080d,transparent:true,opacity:.4,depthWrite:false}));s.rotation.x=-Math.PI/2;s.position.y=.025;return s;}
 makeEnemy(e){const root=new T.Group(),body=new T.Group();root.add(body);const big=e.type==='brute',fast=e.type==='skitter';const skin=this.mat(big?0x373c45:0x192331);const scale=big?1.72:fast?.72:1;root.scale.setScalar(scale);this.ball(body,0,.63,0,.42,.49,.34,skin,1);this.ball(body,0,1.08,.1,.39,.35,.36,skin,2);this.ball(body,0,.31,-.18,.32,.3,.27,skin);if(big){this.ball(body,0,.85,-.15,.62,.49,.4,0x454a4c);this.box(body,0,.6,.23,.7,.23,.08,0x596167);for(const x of [-.43,.43])this.ball(body,x,1,-.05,.25,.22,.25,0x585d5b);this.ball(body,-.15,1.29,.1,.24,.11,.23,0x7d8278);}
 const eyes=[];for(const x of [-.155,.155]){this.ball(body,x,1.15,.407,.056,.092,.047,this.mat(0xffeaa1,.5,3),2);eyes.push(this.glow(body,x,1.15,.44,.45,0xffd469,.8));}const limbs=[];for(const x of [-1,1]){const a=new T.Group();a.position.set(x*.37,.87,.03);body.add(a);this.ball(a,x*.06,-.19,.08,.13,.29,.14,skin);this.ball(a,x*.12,-.38,.18,.16,.13,.17,skin);for(let i=0;i<3;i++){const claw=this.mesh(new T.ConeGeometry(.035,.21,5),0x75817a,a,x*.12+(i-1)*.09,-.47,.22);claw.rotation.x=-.6;}limbs.push(a);this.ball(body,x*.23,.2,.09,.15,.21,.22,skin);}
 root.userData={body,limbs,eyes,base:scale};root.add(this.shadow(.62));const warn=this.ring(.9,0xff765d,.9);warn.scale.setScalar(1/scale);root.add(warn);root.userData.warn=warn;this.scene.add(root);return root;}
 makeBeam(){const count=52;const geo=new T.BufferGeometry();geo.setAttribute('position',new T.BufferAttribute(new Float32Array((count+2)*3),3));geo.setAttribute('uv',new T.BufferAttribute(new Float32Array((count+2)*2),2));const indices=[];for(let i=0;i<count;i++)indices.push(0,i+1,i+2);geo.setIndex(indices);const mat=new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,blending:T.AdditiveBlending,vertexShader:'varying vec2 v;void main(){v=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 v;void main(){float edge=pow(max(0.,1.-abs(v.x)),.55);float fade=pow(1.-v.y,1.4);gl_FragColor=vec4(1.,.83,.42,edge*fade*.38);}'});const m=new T.Mesh(geo,mat);m.frustumCulled=false;return m;}
 crate(p,x,z,w=1.5,d=1.5){this.box(p,x,.65,z,w,1.3,d,0x66533a);for(let i=0;i<4;i++)this.box(p,x,.17+i*.3,z+d/2+.02,w-.12,.035,.035,0x332d25);for(const k of [-1,1]){this.box(p,x+k*(w/2-.09),.67,z+d/2+.04,.13,1.3,.09,0x967957);this.box(p,x,.67,z+k*(d/2-.08),w,.1,.1,0x9a7e56);}const b=this.box(p,x,.68,z+d/2+.1,.11,Math.hypot(w,1.2),.09,0x8a7050);b.rotation.z=-Math.atan(w/1.2);this.box(p,x,1.33,z,w,.1,d,0x806845);}
 car(p,o){const g=new T.Group();g.position.set(o.x,0,o.z);p.add(g);const w=o.w;this.box(g,0,.66,0,w,.64,1.9,0x203e57);this.box(g,-.15,1.18,0,w*.48,.64,1.65,0x294455);this.box(g,-.15,1.52,0,w*.46,.12,1.67,0x40515a);for(const z of [-.86,.86]){this.box(g,-.15,1.21,z,w*.39,.42,.025,this.mat(0x192e39,.3));this.box(g,-.16,1.22,z,.09,.57,.045,0x7a7c6d);this.box(g,0,.77,z*1.13,w-.1,.06,.07,0x646c6c);}for(const x of [-w*.31,w*.31])for(const z of [-.98,.98]){const tire=this.cylinder(g,x,.4,z,.37,.37,.22,0x111b21,12);tire.rotation.x=Math.PI/2;const cap=this.cylinder(g,x,.4,z*1.12,.18,.18,.03,0x536168,10);cap.rotation.x=Math.PI/2;}for(const z of [-.62,.62]){this.box(g,w/2+.015,.77,z,.03,.18,.33,this.mat(0xe7bc73,.4,.9));this.box(g,-w/2-.01,.77,z,.03,.19,.27,this.mat(0x813931,.5,.4));}this.box(g,w/2+.05,.46,0,.12,.13,1.9,0x647477);for(let i=0;i<12;i++)this.box(g,(this.random()-.5)*w,1.02,(this.random()-.5)*1.8,.12+this.random()*.22,.02,.14,0x514533);}
 lamp(p,x,z){this.cylinder(p,x,1.8,z,.06,.11,3.6,0x293a40);this.box(p,x+.26,3.55,z,.6,.09,.1,0x34464a);this.cylinder(p,x+.5,3.43,z,.25,.38,.2,0x293a40);this.cylinder(p,x+.5,3.32,z,.19,.19,.06,this.mat(0xffe7aa,.5,2));this.glow(p,x+.5,3.25,z,2.3,0xffc972,.48);const pool=new T.Mesh(new T.CircleGeometry(3.8,40),new T.MeshBasicMaterial({map:this.glowTexture,color:0xffbf70,transparent:true,opacity:.23,depthWrite:false,blending:T.AdditiveBlending}));pool.rotation.x=-Math.PI/2;pool.position.set(x+.5,.035,z);p.add(pool);this.lamps.push({x,z});}
 fence(p,x,z,length,axis='x'){const g=new T.Group();g.position.set(x,0,z);if(axis==='z')g.rotation.y=Math.PI/2;p.add(g);for(let a=-length/2;a<=length/2+.1;a+=2.5){this.cylinder(g,a,.82,0,.055,.07,1.64,0x577074,6);}for(const y of [.28,1.47])this.box(g,0,y,0,length,.045,.045,0x526b6d);const points=[];for(let a=-length/2;a<length/2;a+=.4){points.push(new V(a,.3,0),new V(Math.min(length/2,a+1.2),1.45,0),new V(a,1.45,0),new V(Math.min(length/2,a+1.2),.3,0));}const mesh=new T.LineSegments(new T.BufferGeometry().setFromPoints(points),new T.LineBasicMaterial({color:0x527071,transparent:true,opacity:.5}));g.add(mesh);}
 build(game){if(this.world){this.scene.remove(this.world);const gs=new Set(),ms=new Set(),ts=new Set();this.world.traverse(o=>{if(o.geometry)gs.add(o.geometry);if(o.material&&!Array.isArray(o.material)&&!Array.from(this.materials.values()).includes(o.material)){ms.add(o.material);if(o.material.map&&o.material.map!==this.glowTexture)ts.add(o.material.map);}});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());ts.forEach(t=>t.dispose());}for(const e of this.enemyMeshes||[])this.removeDynamic(e);for(const e of this.effects)this.removeDynamic(e.mesh);this.effects=[];this.world=new T.Group();this.scene.add(this.world);this.random=rng(game.config.seed);this.lamps=[];const p=this.world,groundMat=new T.MeshStandardMaterial({map:this.floorTexture(game.config.seed,game.config.theme.floor),roughness:.99});this.box(p,0,-.18,0,57,.3,58,groundMat);
 const theme=game.config.theme;
 for(const room of game.config.rooms){
  this.box(p,room.x,.012,room.z,room.w,.04,room.d,theme.room);
  for(let z=room.z-room.d/2+.5;z<room.z+room.d/2;z+=1)this.box(p,room.x,.036,z,room.w,.008,.025,0x253738);
  for(let x=room.x-room.w/2+.5;x<room.x+room.w/2;x+=1)this.box(p,x,.037,room.z,.025,.008,room.d,0x2b3b3b);
 }
 for(const o of game.obstacles){
  if(o.kind==='wall'){
   this.box(p,o.x,.48,o.z,o.w,.96,o.d,theme.wall);
   this.box(p,o.x,1.02,o.z,o.w,.12,o.d,theme.cap);
  }else if(o.kind==='car')this.car(p,o);else this.crate(p,o.x,o.z,o.w,o.d);
 }
 const warning=this.text('STAY\nIN LIGHT',2.5,1.3,'#b7b0cc',theme.room);
 warning.rotation.x=-Math.PI/2;warning.position.set(game.config.start.x,.065,game.config.start.z-1.5);p.add(warning);
 for(const lamp of game.config.lamps)this.lamp(p,lamp.x,lamp.z);
 const greens=[0x2d493d,0x385745,0x244535,0x45634a,0x233b39];
 for(const room of game.config.rooms){for(let i=0;i<(game.stage%5===2?12:3);i++){
  const x=room.x+(this.random()-.5)*Math.max(1,room.w-1),z=room.z+(this.random()-.5)*Math.max(1,room.d-1);
  if(Math.hypot(x-game.config.key.x,z-game.config.key.z)<1.5||Math.hypot(x-game.config.exit.x,z-game.config.exit.z)<1.5)continue;
  const size=.12+this.random()*.17;this.ball(p,x,.09,z,size,.14,size,greens[i%5],0);
 }}
 this.keyMesh=new T.Group();this.keyMesh.position.set(game.config.key.x,1,game.config.key.z);const keymat=this.mat(0xffd372,.3,1);const hoop=this.mesh(new T.TorusGeometry(.22,.07,6,16),keymat,this.keyMesh);this.box(this.keyMesh,0,-.36,0,.1,.6,.1,keymat);this.box(this.keyMesh,.12,-.58,0,.24,.1,.1,keymat);this.glow(this.keyMesh,0,0,0,2.3,0xffd56e,.7);p.add(this.keyMesh);this.keyRing=this.ring(1.1,0xffd87b,.5);this.keyRing.position.set(game.config.key.x,.05,game.config.key.z);p.add(this.keyRing);
 this.exitMesh=new T.Group();this.exitMesh.position.set(game.config.exit.x,0,game.config.exit.z);for(const x of [-1.25,1.25])this.box(this.exitMesh,x,1.5,0,.22,3,.25,0x6e807b);this.box(this.exitMesh,0,3,0,2.7,.2,.25,0x6e807b);const exitSign=this.text('EXIT →',2,.6,'#a4eaca','#233e38');exitSign.position.set(0,3.55,0);this.exitMesh.add(exitSign);this.exitRing=this.ring(1.45,0x77e8bd,.55);this.exitMesh.add(this.exitRing);this.exitGlow=this.glow(this.exitMesh,0,1.5,0,4,0x6cddbc,.25);p.add(this.exitMesh);
 this.pickupMeshes=new Map();this.enemyMeshes=game.enemies.map(e=>this.makeEnemy(e));this.camX=game.player.x;this.camZ=game.player.z;this.batchStatic();}
 batchStatic(){this.world.updateMatrixWorld(true);const groups=new Map();const dynamic=new Set();this.keyMesh.traverse(o=>dynamic.add(o));this.exitMesh.traverse(o=>dynamic.add(o));dynamic.add(this.keyRing);this.world.traverse(o=>{if(!o.isMesh||dynamic.has(o)||Array.isArray(o.material)||o.material.transparent||o.material.map||!Array.from(this.materials.values()).includes(o.material))return;const key=o.material.uuid;if(!groups.has(key))groups.set(key,{mat:o.material,meshes:[]});groups.get(key).meshes.push(o);});for(const {mat,meshes}of groups.values()){if(meshes.length<2)continue;const geometries=meshes.map(m=>{const g=m.geometry.clone().applyMatrix4(m.matrixWorld);g.deleteAttribute('uv');return g.index?g.toNonIndexed():g;});const merged=mergeGeometries(geometries);if(merged){const m=new T.Mesh(merged,mat);m.castShadow=true;m.receiveShadow=true;this.world.add(m);meshes.forEach(m=>{m.removeFromParent();m.geometry.dispose();});}geometries.forEach(g=>g.dispose());}}
 removeDynamic(root){root.removeFromParent();root.traverse(m=>{m.geometry?.dispose();if(m.material&&!Array.from(this.materials.values()).includes(m.material))m.material.dispose();});}
 burst(x,z,big=false){for(let i=0;i<(big?26:15);i++){const mesh=this.mesh(new T.IcosahedronGeometry(.05+Math.random()*.1,0),this.mat(i%3?0xffdf91:0x8bdbcf,.5,1),this.scene,x,.4+Math.random(),z);this.effects.push({mesh,vx:(Math.random()-.5)*5,vz:(Math.random()-.5)*5,vy:2+Math.random()*3,life:.55+Math.random()*.4,max:1});}const ring=this.ring(.5,big?0xffc979:0xffe7a7,.8);ring.position.set(x,.1,z);this.scene.add(ring);this.effects.push({mesh:ring,ring:true,life:.5,max:.5,vx:0,vz:0,vy:0});}
 updateBeam(game){const p=game.player,range=game.range,positions=this.cone.geometry.attributes.position,uv=this.cone.geometry.attributes.uv;const ox=p.x+Math.sin(p.angle)*.65+Math.cos(p.angle)*.3,oz=p.z+Math.cos(p.angle)*.65-Math.sin(p.angle)*.3;positions.setXYZ(0,ox,1.03,oz);uv.setXY(0,0,0);for(let i=0;i<=52;i++){const a=p.angle+(i/52*2-1)*game.halfAngle;let d=range;const dx=Math.sin(a),dz=Math.cos(a);for(const o of game.obstacles){let lo=0,hi=range;for(const [v,dir,min,max]of[[ox,dx,o.x-o.w/2,o.x+o.w/2],[oz,dz,o.z-o.d/2,o.z+o.d/2]]){if(Math.abs(dir)<1e-8){if(v<min||v>max){lo=range+1;break;}}else{const a=(min-v)/dir,b=(max-v)/dir;lo=Math.max(lo,Math.min(a,b));hi=Math.min(hi,Math.max(a,b));}}if(lo<=hi&&lo<d)d=Math.max(.01,lo);}positions.setXYZ(i+1,ox+dx*d,.08,oz+dz*d);uv.setXY(i+1,i/52*2-1,1);}positions.needsUpdate=true;uv.needsUpdate=true;this.spot.position.set(ox,1.25,oz);this.spot.target.position.set(ox+Math.sin(p.angle)*6,.01,oz+Math.cos(p.angle)*6);this.spot.angle=game.halfAngle;this.cone.visible=game.lit;this.spot.intensity=game.lit?90:4;this.heroGlow.material.opacity=game.lit?.85:.25;}
 render(game,dt,title=false){const p=game.player,t=game.time;this.hero.position.set(p.x,0,p.z);this.hero.rotation.y=p.angle;const moving=title?false:Math.hypot(p.x-(this.lastX??p.x),p.z-(this.lastZ??p.z))>.001;this.lastX=p.x;this.lastZ=p.z;this.hero.userData.body.position.y=moving?Math.sin(t*17)*.045:Math.sin(t*2)*.012;this.heroLegs.forEach((l,i)=>l.rotation.x=moving?Math.sin(t*17+i*Math.PI)*.55:0);this.hero.visible=!(p.invulnerable>0&&Math.floor(t*13)%2&&p.hp<5);this.personal.position.set(p.x,2.3,p.z);this.aimRing.position.set(p.x,.035,p.z);this.aimRing.material.opacity=.2+Math.sin(t*2)*.04;
 for(let i=0;i<game.enemies.length;i++){const e=game.enemies[i],m=this.enemyMeshes[i];m.position.set(e.x,0,e.z);m.rotation.y=e.angle;const ud=m.userData;m.visible=e.death<.45;if(e.hp<=0){m.scale.setScalar(ud.base*Math.max(.001,1-e.death/.45));m.position.y=e.death*.8;continue;}m.scale.setScalar(ud.base);ud.body.position.y=Math.sin(t*(e.state==='hunt'?9:3)+e.phase)*.055;ud.body.rotation.z=Math.sin(t*5+e.phase)*.04*(e.exposure>0?2:1);ud.limbs.forEach((l,j)=>l.rotation.x=Math.sin(t*7+e.phase+j*Math.PI)*.3);ud.warn.visible=e.state==='windup';ud.warn.scale.setScalar((1+(1-e.timer)*.8)/ud.base);ud.eyes.forEach(g=>g.material.color.set(e.state==='windup'?0xff573b:0xffdd8a));}
 this.updateBeam(game);this.keyMesh.visible=game.keyAvailable&&!game.hasKey;this.keyRing.visible=this.keyMesh.visible;this.keyMesh.position.y=1.3+Math.sin(t*3)*.18;this.keyMesh.rotation.y=t*1.5;this.exitRing.material.opacity=game.hasKey?.6:.12;this.exitGlow.material.opacity=game.hasKey?.7:.08;
 for(let i=0;i<game.pickups.length;i++){const q=game.pickups[i];let m=this.pickupMeshes.get(i);if(!m){m=new T.Group();const color=q.type==='heal'?0xe47766:0xecc671;if(q.type==='heal'){this.box(m,0,.3,0,.45,.45,.22,0xae4c43);this.box(m,0,.33,.12,.09,.29,.02,0xffe2ce);this.box(m,0,.33,.13,.29,.09,.02,0xffe2ce);}else{this.cylinder(m,0,.33,0,.14,.14,.5,color,8);this.cylinder(m,0,.6,0,.07,.07,.07,0xcfcec1,8);}this.glow(m,0,.3,0,1.4,color,.36);this.world.add(m);this.pickupMeshes.set(i,m);}m.visible=!q.taken;m.position.set(q.x,.18+Math.sin(t*3+i)*.1,q.z);m.rotation.y=t;}
 for(let i=this.effects.length-1;i>=0;i--){const e=this.effects[i];e.life-=dt;if(e.life<=0){this.removeDynamic(e.mesh);this.effects.splice(i,1);continue;}if(e.ring){e.mesh.scale.multiplyScalar(1+dt*6);e.mesh.material.opacity=e.life;}else{e.mesh.position.x+=e.vx*dt;e.mesh.position.z+=e.vz*dt;e.mesh.position.y+=e.vy*dt;e.vy-=dt*8;e.mesh.scale.setScalar(Math.min(1,e.life*3));}}
 const factor=1-Math.exp(-dt*5);const tx=title?p.x-3:clamp(p.x,-16,16),tz=title?p.z:clamp(p.z,-18,18);this.camX+=(tx-this.camX)*factor;this.camZ+=(tz-this.camZ)*factor;const shake=game.flash>0?game.flash*.13:0;this.camera.position.set(this.camX+Math.sin(t*81)*shake,27,this.camZ+19);this.camera.lookAt(this.camX,0,this.camZ-2);this.renderer.render(this.scene,this.camera);}
 resize(){const w=innerWidth,h=innerHeight;this.renderer.setSize(w,h,false);const aspect=w/h,span=(aspect<1?25:22)/CAMERA_ZOOM;this.camera.left=-span*aspect/2;this.camera.right=span*aspect/2;this.camera.top=span/2;this.camera.bottom=-span/2;this.camera.updateProjectionMatrix();}
}
